# Generated by Django 3.0.3 on 2020-07-14 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swapnic_blog', '0002_auto_20200714_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 5, 48, 26, 426777, tzinfo=utc)),
        ),
    ]
