# Generated by Django 3.0.3 on 2020-07-14 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swapnic_blog', '0004_auto_20200714_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 6, 40, 12, 534028, tzinfo=utc)),
        ),
    ]
