# Generated by Django 3.0.3 on 2020-07-14 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swapnic_blog', '0005_auto_20200714_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 6, 42, 19, 545220, tzinfo=utc)),
        ),
    ]
